### PR TITLE
cjs transform searches for top level requires only

### PR DESCRIPTION
**Pull request by gmathieu**
#29

## Known issues

A [new line](https://github.com/5to6/5to6-codemod/pull/30/files#diff-e1bf2dc9923a5da099687c7f448f6dd2R3) is added after declarations with stacked comments. I believe it's an issue with the parser.

## changelog

- cjs transform searches for top level requires only
- cjs transform now preserves comments (both top-level and inline)
- cjs transform now converts require maps (ex. `var lookup = { foo: require('path/to/foo'), bar: require('path/to/bar')`)

Playground: https://astexplorer.net/#/gist/d614f671387956fab190f1a622ef6fa6/588f60fa84938de44a170da6890478f22cec0ed5

### CODE REVIEW

**Comment by jsnmoon** [comment]
Hey gmathieu, this is awesome! I'd been working on the same issue by detecting if the ExpressionStatement had a BlockStatement somewhere along the parent chain. Your solution seems  faster & more straightforward.

FYI for the newline issue: both [jscodeshift](https://github.com/facebook/jscodeshift/issues/185) and [recast](https://github.com/benjamn/recast/issues/371) have an issue filed regarding this.

**Comment by gmathieu** [comment]
FWIW: I tested this on our codebase (~3000 files) and the newline was never an issue. Although, we don't typically comment our imports. Thanks for the heads up @jsnmoon. I thought I was taking crazy pills 😄 

Who should I assign this review to?

**Comment by gmathieu** [comment]
I'll update the PR with a missed case for preserving comments. I might also add a conversion for require lookups where dynamic requires are forbidden (for grep-ability).

From:
```
var PATHS = {
  x: require('path/to/x'),
  y: require('path/to/y')
}
```

To:
```
import x from 'path/to/x'
import y from 'path/to/y'

var PATHS = {
  x,
  y,
}
```

**Comment by gmathieu** [comment]
@xjamundx this is ready for review when you are.

**Comment by xjamundx** [comment]
I think you'll need to rebase, but I'll check it out as soon yas you do that!

**Comment by xjamundx** [comment]
Also @gmathieu since I'm busy do you want to become a maintainer of this project?

**Comment by gmathieu** [comment]
@xjamundx rebase complete. I'm happy to give it a go. Fair warning, I oversee a team of 15 so can get pretty swamp myself. :)

**Comment by xjamundx** [comment]
let's ust move this along 👍

**Pull request merged**
