### PR TITLE
var { module1, module2 } = require('module3) => import { module1, module2 } from 'module3';

### PR DESCRIPTION
**Pull request by frodosamoa**
Also, I took a look at `master` and three tests are failing off the bat. This PR only adds one error which seems to be wrong:
```
1) CJS transform should convert require('jquery') -> import 'jquery' :

      AssertionError: '// CJS top comment\n\nimport jamis from \'jquery\';\nimport $ from \'jquery\';\nimport $ from \'jquery\';\nimport \'something\' == '// CJS top comment\n\nimport jamis from \'jquery\';\nimport $ from \'jquery\';\nimport $ from \'jquery\';\nimport \'something\'
      + expected - actual

       var jamis = 'bar', bar, foo = 'bar';

       import {routeTo} from '../routeHelper';
       import {pluck as fetch} from '../someUtil';
      -import {includes, pick} from 'lodash';
      +import {includes, pick} from 'lodash';

      at Context.<anonymous> (test/transforms/cjs.js:25:12)
```

It is complaining about the last line even though they look totally indentical. I'm thinking maybe a whitespace issue?

### CODE REVIEW

**Comment by xjamundx** [comment]
fancy thanks!

**Comment by frodosamoa** [comment]
PR should be good to go! Let me know if I missed anything or if I can help iron out the issues on `master`. Test were complaining about code that had comments in them.

**Comment by frodosamoa** [comment]
PR should be good to go! Let me know if I missed anything or if I can help iron out the issues on `master`. Test were complaining about code that had comments in them.

**Comment by frodosamoa** [comment]
PR should be good to go! Let me know if I missed anything or if I can help iron out the issues on `master`. Test were complaining about code that had comments in them.

**Comment by frodosamoa** [comment]
If I change the broken assertion to this `assert.equal(result.trim(), expectedSrc.trim());` within the `cjs.js` file, the test passes 😞

**Comment by xjamundx** [comment]
will take a look later tonight ,thanks for your hard work

**Comment by xjamundx** [comment]
so yeah a few tests failing. I'd be fine with the `trim()` hack for now until we get a better handle on whitespace issues in general 👍

**Comment by frodosamoa** [comment]
Alright, I'll edit my PR to include the `trim`!

**Comment by frodosamoa** [comment]
@xjamundx Test has been update to trim `result` and `expectedSrc`.

**Comment by xjamundx** [comment]
Let me test this out. sorry for the delay

**Pull request merged**
