### PR TITLE
Improves comment handling in CommonJS import transformation

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes two known issues and added a corresponding test.

### CODE REVIEW

**Comment by jsnmoon** [comment]
Howdy @gmathieu, do you think we could merge this in?

**Comment by xjamundx** [comment]
This is pretty sweet

**Comment by xjamundx** [comment]
ooops, we just merged some other stuff in. if you get this rebased today I'll merge and publish them all together.

**Comment by jsnmoon** [comment]
Got it! I'll go ahead and rebase this in a few minutes.

**Comment by jsnmoon** [comment]
Rebase complete!

**Comment by xjamundx** [comment]
I will try to publish these changes in the next 30 minutes

**Comment by xjamundx** [comment]
https://github.com/5to6/5to6-codemod/blob/master/CHANGELOG.md#160

**Comment by xjamundx** [comment]
published

**Pull request merged**
