### PR TITLE
Added travis ci support

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by xjamundx** [comment]
thanks!

**Comment by nickmccurdy** [comment]
@xjamundx I'm seeing `This is not an active repository` [on Travis](https://travis-ci.org/5to6/5to6-codemod), could you please check that the repository is enabled in your Travis account?

**Comment by xjamundx** [comment]
I believe it's not been activated :)

**Comment by jsnmoon** [comment]
Travis builds have now been [activated](https://travis-ci.org/5to6/5to6-codemod/builds/235000374)!

**Pull request merged**
